name: Auto release

on:
  push

jobs:
  build:
    name: Build by Go${{ matrix.go-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version:
          - 1.16
          - 1.18
          - 1.19

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build
        run: bash ./buildAllPlatforms.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Go${{ matrix.go-version }}
          path: bin/*

  release:
    name: Release the build by Go1.19
    if: startsWith(github.ref, 'refs/tags')
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: Go1.19
          path: bin/

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files:
            bin/*
